### ISSUE TITLE
Admin mobile content outside of viewport when navigation menu is open

### ISSUE THREAD

**Issue by bull5-i** [opencart/opencart#1791]
Currently when viewing the admin pages in a mobile device with screen width less than 768px with the navigation menu is opened, the page content is pushed off the screen due to following stylesheet rule in
`/upload/admin/view/stylesheet/stylesheet.css`:

``` css
@media (max-width: 767px) {
#column-left.active + #content {
    position: relative;
    left: 235px;
}
}
```

Pushing content off the screen so it is not accessible is definitely not the right thing to do. Instead I would use `margin-left: 235px;` (this way the `#content` div width will be reduced to what is left of the 235px margin) or **_even better**_ `left: 0;` so the navigation menu will overlay the `#content` div which will keep the full page width. With such small screen sizes keeping the navigation menu opened while viewing or modifying content is not practical anyway, so overlaying the menu seems to be more appropriate solution.
