### ISSUE TITLE
Bootstrap info button showing blue border 

### ISSUE THREAD

**Issue by nuke123** [opencart/opencart#3126]
catalog/view/theme/default/stylesheet/stylesheet.css

Missing focus and border color to overwrite bootstrap

```css
.btn-info:hover, .btn-info:active, .btn-info.active, .btn-info.disabled, .btn-info[disabled] {
	background-image: none;
	background-color: #df5c39;
}
```
