### ISSUE TITLE
Simple Error Sign for Admin Theme

### ISSUE THREAD

**Issue by erdembey** [opencart/opencart#608]
I want to propose a simple css modification to admin theme.
We can add a simple font awesome icon to the error div. 

``` css
.alert-error:before{
    content: "\f05e\00a0";
    font-family: FontAwesome;
}
```
